### ISSUE TITLE
I was also lied to

### ISSUE THREAD

**Issue by GaryQian** [Richarizardd/One-Line-K-Means#2]
The README.md contains two lines, and along with the python code, makes a total of three lines. Not one.

I propose the python be moved to README.md, and the code be put on the same line as the text of the readme, which would go in a comment enclosed in ''' '''.

**Comment by Richarizardd** [comment]
Hi Gary,

Thank you for bringing this to my attention. Will see what I can do.

Warm Regards,
-R

**Comment by Richarizardd** [comment]
Hi Gary,

Apologies for making an egregious error. You're absolutely right. If you think about it, my README was twice as long as my python script, which is simply unacceptable. I accepted your proposed changes, and now it is true one-liner.

Sincerely,
-R

**Comment by GaryQian** [comment]
Much better. I can once again sleep at night. Thank you for solving this enormous wrong in the world
