### ISSUE TITLE
Another day, Another lie

### ISSUE THREAD

**Issue by GaryQian** [Richarizardd/One-Line-K-Means#3]
It appears that once again, this kmeans implementation is not one line. The title of the repo counts as one line, and the text counts as another. This makes a total of three lines.

Please fix this, as it is blocking my release.

**Comment by Richarizardd** [comment]
Dear Mr. Qian,

I am sorry that this is blocking your release. In an ideal world, the title of the repo would not count as a line, but alas. I also noticed that the "\n" character took up another line in the file. I updated the codebase so at least the K-Means implementation in k_means.py is now truly, one line. Thank you so much for pointing out this inconsistency. I really appreciate your attention-to-detail to this public repository, and I greatly admire your strong commitment to open-source.


Warm Regards,
-R

**Comment by GaryQian** [comment]
Thank you for fixing a big part of this.

I understand that sometimes technical limitations prevent what we truly desire. I will work on a workaround to the title lines.
